# Generated by Django 3.0.4 on 2020-04-02 03:27

from django.db import migrations, models
import django.db.models.deletion
import markets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.IntegerField(choices=[(1, 'active'), (0, 'inactive')], default=1)),
                ('image', models.ImageField(blank=True, height_field=50, max_length=250, null=True, upload_to=markets.models.category_path, width_field=50)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('addresses', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('city', models.CharField(max_length=150)),
                ('minimun_price', models.FloatField()),
                ('state', models.IntegerField(choices=[(1, 'active'), (0, 'inactive')], default=1)),
                ('categories', models.ManyToManyField(to='markets.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_telephone', models.IntegerField(choices=[(0, 'N/A'), (1, 'landline'), (2, 'mobile'), (3, 'whatsapp')], default=1)),
                ('number', models.CharField(max_length=150)),
                ('first', models.BooleanField(default=False)),
                ('state', models.IntegerField(choices=[(1, 'active'), (0, 'inactive')], default=1)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.Market', verbose_name='Market')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('size', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
                ('image', models.ImageField(height_field=50, max_length=250, upload_to=markets.models.product_path, width_field=50)),
                ('categories', models.ManyToManyField(to='markets.Category')),
            ],
        ),
        migrations.AddField(
            model_name='market',
            name='products',
            field=models.ManyToManyField(to='markets.Product'),
        ),
    ]
