# Generated by Django 3.0.4 on 2020-04-02 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'N/A'), (1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (5, 'Domingo'), (6, 'Todos los días')], default=1)),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('state', models.IntegerField(choices=[(1, 'active'), (0, 'inactive')], default=1)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.Market', verbose_name='Market')),
            ],
        ),
    ]
